### ISSUE TITLE
How to sample results on LSUN dataset?

### ISSUE THREAD

**Issue by XinYu-Andy** [jychoi118/ilvr_adm#10]
Hi,
Thanks for your great job on diffusion model! 
I am wondering if I can download the pre-train model on LSUN from  [improved-diffusion](https://github.com/openai/improved-diffusion)
 to sample in your code? I find there are some mismatching when loading the parameters. Have you modified the code base?
Thank you.

**Comment by jychoi118** [comment]
I did not change the model implementation. However, we used smaller model configuration. 
You may check the MODEL FLAGS (e.g., `--num_res_blocks`,  `--num_heads `)
