### ISSUE TITLE
Possible errors about using q_sample(x, t)

### ISSUE THREAD

**Issue by ZGCTroy** [jychoi118/ilvr_adm#13]
![image](https://user-images.githubusercontent.com/28867789/168046416-cbdb8c7d-a180-4833-af59-bf3cc4528f28.png)
Thanks for your impressive contribution !
You implemented y_{t-1} by using the method q_sample(y, t). However, the right way is q_sample(y, t-1). Is there exisits any errors here?
![image](https://user-images.githubusercontent.com/28867789/168047922-bb2cc9d7-3ab8-4ef0-9ea5-e0201aa318f4.png)

**Comment by jychoi118** [comment]
Yes, t should be modified to t-1. Thank you for letting me know the error. 

While the experiments in the paper were done correctly with t-1, I made a mistake while moving to the [guided-diffusion](https://github.com/openai/guided-diffusion) codebase. 

In fact, the mistakenly added noise (variance \beta_t) is small enough to be eliminated by downsampling operation, thus the samples are fine even with t.

**Comment by ZGCTroy** [comment]
Thanks for your reply. I agree with you that "the mistakenly added noise (variance \beta_t) is small enough to be eliminated by downsampling operation, thus the samples are fine even with t".
