### ISSUE TITLE
DDIM sampling 

### ISSUE THREAD

**Issue by zacharyclam** [jychoi118/ilvr_adm#14]
Thanks for the awesome work.
Whether I can use ILVR sampling based on the ddim sampling scheme? I try to use ddim sampling scheme with ILVR, but the result will be very blury.

**Comment by jychoi118** [comment]
Yes, samples from ILVR + DDIM have either blur or noise artifacts, probably due to the aliasing error of the image resizer. The Brownian noise added in DDPM sampling corrects such errors. I believe finding a better conditioning scheme for DDIM will be a good future research direction.
