### ISSUE TITLE
Confusing about timesteps

### ISSUE THREAD

**Issue by zacharyclam** [jychoi118/ilvr_adm#15]
Thanks for the fantastic work.
In the paper, you said that trained unconditional DDPM with publicly available  PyTorch implementation(https://github.com/rosinality/ denoising-diffusion-pytorch) has 1000 timesteps during the training stage. But during the inference stage, directly use 100 steps without respacing. How does it work? Is there a problem with my understanding, and no relevant explanation is found in the paper.

**Comment by jychoi118** [comment]
Sorry for late reply.
The model is trained with 1000 timesteps and samples are generated with 100 sampling steps (using respacing), as indicated in the sampling script of readme: `--diffusion_steps 1000 --timestep_respacing 100`.
