### ISSUE TITLE
Questions about style transfer

### ISSUE THREAD

**Issue by SkrBully** [jychoi118/ilvr_adm#17]
Hi teams!
 
Thanks for sharing your code and excellent work at first! I have tried your sampling code on my GPUs and got great outputs. I'm wondering whether your model can produce the outputs, which has the same texture shape of inputs but get colorized as reference pictures style?  I have tried big N (e.g.,N=64) as you mentioned in the paper which can preserve only the coarse aspect (e.g., color scheme) of the reference but didn't get a good performance. So could I ask you any ideas to solve this problem?

(What I have done so far: I used image_train.py and domain A datasets(256x256) to train the model ema_0.9999_010000.pt. And then use some 256x256 images in domain B with big N to generate outputs.)

Thanks in advance!

**Comment by jychoi118** [comment]
I think you need to train the model longer. While I cannot guess your dataset and batch size, 10000 training steps seems too short. Try with a model trained with at least 400000 training steps

**Comment by xiayhh** [comment]
> 

Hi, I wanted to ask did you end up with good texture features in the style transfer?
