### ISSUE TITLE
Can this model be applied to other data modalities?

### ISSUE THREAD

**Issue by ZDstandup** [jychoi118/ilvr_adm#21]
Hi, authors. Can this model be applied to other data modalities? such as audio, text,...
Have you tried it?
Hope that you can give me some suggestions. Thanks in advance!

**Comment by jychoi118** [comment]
Directly using our method to those modalities might be difficult. Low frequency audio or masked texts may not contain semantics like low-resolution images. Meanwhile, [guided-tts](https://proceedings.mlr.press/v162/kim22d.html) uses additional classifier for guiding text-to-speech models.

**Comment by ZDstandup** [comment]
Hi, @jychoi118 , what I understand is that the key factor in your method is the low-pass filtering operation. After these operations, the low-resolution images contain the semantics or the structure information. Finally, the generated images might share the semantics of the reference images.  So what I should try to do is produce the semantics of the reference data (like audio,...) in my tasks?
