### ISSUE TITLE
Questions about the training process

### ISSUE THREAD

**Issue by zy-charon** [jychoi118/ilvr_adm#27]
Hi, thank you very much for your great work. I have trained a model with class_cond as true before, and using this model to directly sample has a torch size mismatch problem. I would like to ask if there are any special requirements for parameter setting if training a diffusion model from scratch. Is it enough to keep the parameter class_cond as false and other parameters to be reasonable?
![error](https://user-images.githubusercontent.com/74723536/220350131-ce2f6e8b-1659-4fc7-a10f-73bf89ca2e7b.png)

**Comment by jychoi118** [comment]
Try setting `--learn_sigma True` when training the model.
The output channel of the model is 6 instead of 3, because the model learns both epsilon and sigma.

**Comment by zy-charon** [comment]
> Try setting `--learn_sigma True` when training the model. The output channel of the model is 6 instead of 3, because the model learns both epsilon and sigma.

Thank you, I'll try again
