### ISSUE TITLE
Question about your paper train

### ISSUE THREAD

**Issue by zhangzhili1112** [jychoi118/ilvr_adm#3]
Hi,
Thanks for sharing the code, I am very interested in your paper.
I just wanted to ask a few questions regarding training:
Your training is the same as guided-diffusion, only the sampling process is modified, right?

**Comment by jychoi118** [comment]
Yes, our concept is to control the sampling process of the pre-trained unconditional model.

**Comment by zhangzhili1112** [comment]
> 



> Yes, our concept is to control the sampling process of the pre-trained unconditional model.

**Comment by zhangzhili1112** [comment]
> Yes, our concept is to control the sampling process of the pre-trained unconditional model.
Thanks  for helping me out

**Comment by zhangzhili1112** [comment]
Embarrassed, I made a mistake to close the problem
