### ISSUE TITLE
Dataset used for training ffhq_10m.pt

### ISSUE THREAD

**Issue by sunyasheng** [jychoi118/ilvr_adm#6]
Thanks for your amazing work and nice sharing. You've said that 10M images are used to train ffhq_10m.pt in your REAME. As far as I know, there are 70000 images in FFHQ dataset. It is a little confusing. So is there any other data I've missed?

**Comment by jychoi118** [comment]
Yes, there are 70000 images in FFHQ. What I meant for 10M is a number of images seen by the model, which is `batch_size x iteration`, or `epoch x 70000`.

**Comment by sunyasheng** [comment]
Thank you very much for quick reply. That makes sense. Since it clarifies my  question, I will close this issue.
