### ISSUE TITLE
Training Requirement for GPU

### ISSUE THREAD

**Issue by KevinGoodman** [jychoi118/ilvr_adm#7]
Excellent work and thanks for sharing your code.
I'm a novice at diffusion models, and I'm concerned about theGPU resource this kind of models need.
I wonder can all the training be done on a single RTX3090.

**Comment by jychoi118** [comment]
Hello,
We trained our unconditional models with a single GPU with 48GB VRAM. It took about 1~2 weeks for FFHQ and AFHQ dataset. However, you might need more resources to train on larger datasets (ImageNet, LSUN). [Diffusion Models Beat GANs on Image Synthesis](https://arxiv.org/abs/2105.05233) spend almost 1000 GPU days to train on those datasets.

**Comment by KevinGoodman** [comment]
Thank you very much for the quick reply.
