### ISSUE TITLE
ilvr_sample hangs at the line "model_kwargs = next(data)"

### ISSUE THREAD

**Issue by vinodrajendran001** [jychoi118/ilvr_adm#8]
Hi,

I am using the FFHQ pt file to load the checkpoint and do the sampling.

I just placed one example image in the ref_imgs/face/ folder and ran the ilvr_sample file as per the README file. But the script hangs at the line ```model_kwargs = next(data)``` .

May I know how to resolve it?

Thanks.

**Comment by jychoi118** [comment]
Sorry for late reply. 
Did you set PYTHONPATH? or maybe you can try --batch_size 1

**Comment by vinodrajendran001** [comment]
I resolved it by setting batch size 1
